Update RenderControl.cpp
anbox/anbox pull request #1678
Opened 2020-11-12 20:15 UTC by novhy

this will make some apps opened correctly,
like google chrome

2020-11-12 21:05 UTC, morphis requested changes
Do you have a list of apps which this helps to make working?

2020-11-12 21:05 UTC, morphis commented on src/anbox/graphics/emugl/RenderControl.cpp
> +    result = "Google ("+result+")";
Can we add spaces in here to honor the overall coding style?

2020-11-12 21:05 UTC, morphis commented on src/anbox/graphics/emugl/RenderControl.cpp
> +    result = "Android Emulator OpenGL ES ("+result+")";
See above

2020-12-02 09:44 UTC, Niek commented
I was hoping this would fix the issues in https://github.com/anbox/anbox/issues/1637 since you mentioned Chrome, but with this PR applied I still get these errors:

```bash
12-02 09:41:48.547  1012  1033 E EGL_emulation: tid 1033: eglCreateContext(919): error 0x3005 (EGL_BAD_CONFIG)
12-02 09:41:48.547  1012  1033 E chromium: [ERROR:gl_context_egl.cc(248)] eglCreateContext failed with error EGL_BAD_CONFIG
12-02 09:41:48.547  1012  1033 E chromium: [ERROR:gpu_channel_manager.cc(749)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
12-02 09:41:48.547  1012  1033 E chromium: [ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
12-02 09:41:48.547  1012  1033 E chromium: [ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
```

2020-12-02 15:53 UTC, novhy commented
im build anbox version from
https://github.com/anbox/anbox/commit/6386cf57bc3a17ff9b89c22f486e459d4c141a6b


patched for ubuntu touch
and android img from

http://anbox.postmarketos.org/

arm64 version

chrome works, gapps works

but after editing /system/etc/permissions

added standard android features

all app in playstore showup

but, chrome,firefox becoming useless again


i think chrome,firefox blocking some opengles extention or some what on device that detected as emulator

just try with standard android img for anbox and that patch

2020-12-02 16:17 UTC, Niek commented
> im build anbox version from
> [6386cf5](https://github.com/anbox/anbox/commit/6386cf57bc3a17ff9b89c22f486e459d4c141a6b)
> 
> patched for ubuntu touch
> and android img from
> 
> http://anbox.postmarketos.org/
> 
> arm64 version
> 
> chrome works, gapps works
> 
> but after editing /system/etc/permissions
> 
> added standard android features
> 
> all app in playstore showup
> 
> but, chrome,firefox becoming useless again
> 
> i think chrome,firefox blocking some opengles extention or some what on device that detected as emulator
> 
> just try with standard android img for anbox and that patch

Which "ubuntu touch patch" are you referring to? I tested anbox (latest master) + this PR + copied android/media/* to /system/etc + http://anbox.postmarketos.org/ image on x86 and I can open Chrome, but cannot load any page.

2020-12-02 17:12 UTC, novhy commented
ubuntu touch patch from anbox ubport github repo,

hmm, chrome open and  adb logs is about segmentation fault in glgetshaderprecisionformat?

2020-12-02 21:55 UTC, Niek commented
@novhy do you have a repo with the source you're building? I have issues merging the ubports repo changes to upstream cleanly. I still haven't been able to run a recent Chrome correctly. It starts up fine, but no page renders (EGL_BAD_CONFIG errors).

2020-12-18 02:11 UTC, kokhui commented
> im build anbox version from
> [6386cf5](https://github.com/anbox/anbox/commit/6386cf57bc3a17ff9b89c22f486e459d4c141a6b)
> 
> patched for ubuntu touch
> and android img from
> 
> http://anbox.postmarketos.org/
> 
> arm64 version
> 
> chrome works, gapps works
> 
> but after editing /system/etc/permissions
> 
> added standard android features
> 
> all app in playstore showup
> 
> but, chrome,firefox becoming useless again
> 
> i think chrome,firefox blocking some opengles extention or some what on device that detected as emulator
> 
> just try with standard android img for anbox and that patch

Hi, can I check does your gapps works in --single window mode? It keep popping up prompt that google services is stopping when I run in that mode.

Using arm64 ver from anbox.postmarketos.org and gapps arm from opengapps.org/. (Running on AWS ec2 arm 64bit instance)

2021-02-09 23:38 UTC, Shatur95 commented
@novhy, what kind of Ubports patches have you applied?

2021-03-13 17:46 UTC, novhy commented
![screenshot20210314_003652703](https://user-images.githubusercontent.com/7148317/111038830-7c780f00-845d-11eb-95af-347e2da0ad23.png)

sorry everyone, that patch is missing something,
i will upload my source later, or finding what cause, and pull request to this repo

2021-03-13 19:06 UTC, Shatur95 commented
@novhy, it would be awesome!

2021-04-02 21:43 UTC, Shatur95 commented
@novhy, any news about it? Sorry for bothering.

2022-04-17 00:17 UTC, closed without merging